apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: anonymous-access-livez
rules:
  - apiGroups: [""]
    resources: ["livez"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: anonymous-access-livez-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anonymous-access-livez
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
