apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-access-livez
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
    resourceNames: ["livez"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-access-livez-binding
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: anonymous-access-livez
  apiGroup: rbac.authorization.k8s.io
